### ISSUE TITLE
Songs uploads do not appear in real-time in user profiles

### ISSUE THREAD

**Issue by rufusdumont** [pablomurasaki/song-a-day-for-a-month#26]
When a songwriter submits a song, it appears in the main feed immediately. However, when the songwriter goes to his/her profile, that new song doesn't appear unless he/she refreshes the page. Can we make it so the song appears in the profile view immediately after it is uploaded without having to refresh the page? And if the song is revoked, it should disappear immediately from the profile page as well.

**Comment by pablomurasaki** [comment]
user profiles now watch for a change in their object and reload songs on change
